language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "QDfSTZSoNLSQqwRVnrdRgc+qDp16cQZ1I4B3VkeZr3w9E+/wLVil4Ix7WVubwvBI/yZd/fu4e7Q4pFkprrxQvgfDi7OcODGBbs73JigQVt1AWMu8mGlmioym0qjwPliKWpd/Sj7sncRDlj5QytJVZH8trIkqpAHjohi242y+FaIwoWN1b/7y/ze4219H6bzf858PrWKrVgRlxohYUCdjKW5V2c/52m8VknCuV1IhHYykLITFL+Lkk5DEx8AndGwrfFL5AQWBAfMeWyb91S9ulELhlxSxa8jIwRhH5pFgvoBVlO0VWytV46grhkhXHl+fAtr9uIUAnb6ixLYtmAG0Imt8QrFQWO+gZ5l7vUe7zwZHqpAqnNzvL/jhwAbWYLOOrvkbvjyE4ISVicZMl57bbBWm98/J6MI2G+tUVIxW7Bpt5rn/PTc2b+Lm51jkgrpw321iILUlpXHvUW/6yKFQTU484jHVxASIp6OE8zUDG3ifjXJn0rhF9LbxVf7l9/oOTDGsXA9UKB9Fvc+BnVGK+eGd5A5y6EMdpVIBTtJmlr058Ud7+AreXnsgjfqFZr05wq/clCMZGLpwXa6fOKYNFb7LjA3yLWRFondc1DIHLEL074lQHVTS7qsWACKqMm7Mah5wvpl/LreA9JjZAXY6TgLgp4YFlpIX3qbpTQoHaBU="
