language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: Vumv+xEbUxUwsDLkO4yHasEE1xvFHBwrhu+QAc1qPQnvWnoJQcYtQu02HB+2NYDZZbjImFMsyERY2Uc8OcUQilH7uaPT854+yP51yCRQTg8yzZ0ksUiBm0FxOlCwy5tum25kMMb8xQ56VBy1npPo3E0p2HpE6Rk00aBw7l701keo7hID0jaizMorbbSrLmw1uL4LoA8i4+bs1WzByXJfHGPP7v4qGzc3jReDg7U62K/QhsMh/vUZGgIOnVbSKsqAl0gQPUXpijsskBowzsF4rEPavZEDjJyy76Mt1msXSqBoN6ccEIwYMbTji6aWJXljo3TNfngcuB41OvWbdxTE0q3COFZXUR96P2rABOe6SKql5/tnNH1X7bM9UCiVmmqdWi5TCMu4ahX7MMd5U+J+4/ASXH92x1W7+rfHxAYlZYylUQeLUBAbC9fWrWx+1jED03YJ98dgLcQWlRGUIzQV9uB6ShRNqjwNZ6Psk1/UlDQkWZYo+fYgc3ZRwEQhEgfBo3AE1nsafhGqNWeHhaW+e23I4+HcoMmDZtfqB9KMCwXyWZuHkoCwOLstkouS04oV9hwhlI4LiAVTD4BeowuvUYdJYKwXqnj9RwX3iz3QVPmbfrntEvDy8Q+WjKfmvjYwuKTmANU+ocriuXwG96JffhKDoHs+K7yzR/T4pRN4z+U=
