language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run build
# - npm run test
deploy:
  provider: firebase
  skip_cleanup: true
  token: 1//03AfPekTDQBUgCgYIARAAGAMSNwF-L9Irh3MHlIt_0DUzj7D6vO7EPTAK-3dOd2_vOeQ8g2vknGiQC6TjhjpfzNfRfecMRWemQi4
